### ISSUE TITLE
Privacy/Security concern - Suggesting about implementing a direct link

### ISSUE THREAD

**Issue by games647** [iAmGio/TeamSpeakJoiner#1]
Here I assume that redirect.iamgio.e is your website:

**This is only a suggestion. If you don't share the same opinion, just write a comment and close this ticket. I have no problem with that.**

Why do you need to redirect the users to your own website instead of redirect the users directly to tsredirect.altervista.org or using the ts3 protocol directly (if that works)?

https://github.com/iAmGio/TeamSpeakJoiner/blob/10513aa222da6b2f4ba93cd524fa99fc322e218e/src/eu/iamgio/teamspeakjoiner/utils/URLBuilder.java#L32

First of depending on your website also means that the complete plugin won't work if cancel the web server hosting contract.

Security:
1. Invalid SSL certificate
2. You could host malicious JavaScript (This doesn't mean I don't trust you. I mean that every server server could be hacked) - see https://observatory.mozilla.org for more details about solving it

Privacy:
You can get the following data about your users
1. Timestamp
2. Browser details
3. IP information and geo data
4. Minecraft username
5. Server name the users wants to join
6. You don't publicly disclose the fact this uses a third-party service.

**Comment by iAmGio** [comment]
Hi,
I can't access to IPs or other users' data. It's only a redirecting website.

> You don't publicly disclose the fact this uses a third-party service.
Minecraft shows the link before opening it.

**Comment by games647** [comment]
>I can't access to IPs or other users' data. It's only a redirecting website.

And every webserver gets the socket data (containing the IP address) for every incoming requesting. It's a required to send the response back. Apache logs that data by default for example.

>It's only a redirecting website.

Just like tsredirect.altervista.org which you are redirecting to. You could just link directly to it or implement it yourself on your server. Then you could also make use of better security standards like https (i.e. with free Let's encrypt certificates) and more.

**Comment by games647** [comment]
Do found a solution?
